### PR TITLE
yank default action for TMUX > 2.4 + MouseDragEnd1Pane

### PR DESCRIPTION
**Pull request by kaliberr44**
Added @yank_action for user to be able to choose copy-pipe or copy-pipe-and-cancel when yanking without put. 

Also added MouseDragEnd1Pane so you don't have to press y after selecting with mouse.

### CODE REVIEW

**Comment by maximbaz** [comment]
> Also added MouseDragEnd1Pane so you don't have to press y after selecting with mouse.

Your current implementation in this PR is against [the Linux convention](https://wiki.archlinux.org/index.php/Clipboard#Background). When we press `y`, we want the contents to be copied in the `clipboard` selection (`xclip -selection clipboard`):

https://github.com/tmux-plugins/tmux-yank/blob/feb9611b7d1c323ca54cd8a5111a53e3e8265b59/scripts/helpers.sh#L21-L22

https://github.com/tmux-plugins/tmux-yank/blob/feb9611b7d1c323ca54cd8a5111a53e3e8265b59/scripts/helpers.sh#L128-L131

However selecting text with a mouse should only affect `primary` selection, never `clipboard` selection.

**Comment by kaliberr44** [comment]
If I would remove the `MouseDragEnd1Pane` would this PR with default yank action be acceptable?

**Comment by maximbaz** [comment]
I have one more suggestion - set the default value of `yank_action_default` to `copy-pipe-and-cancel` instead of `copy-pipe`, because it seems right now you are changing the default behavior for every other user and I would recommend avoiding that.

I'm not an official maintainer of this project, but besides these two comments it seems OK to me 👍

**Comment by kaliberr44** [comment]
I removed `MouseDragEnd1Pane` and set `yank_action_default` to `copy-pipe-and-cancel`

**Comment by offero** [comment]
This will make life much better. Please merge soon!

**Comment by mcanfield** [comment]
@kaliberr44 
The stack exchange answer [How to successfully copy and paste with a mouse from tmux](https://unix.stackexchange.com/questions/318281/how-to-successfully-copy-and-paste-with-a-mouse-from-tmux) uses the `MouseDragEnd1Pane` that you proposed. I ended up modifying it to use pbcopy:

```
# Enable mouse mode
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down

# To copy, left click and drag to highlight text
# once you release left click highlighted text will disappear and will automatically be available in clibboard
# Use vim keybindings in copy mode
setw -g mode-keys vi

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

Perhaps you could repackage what you did coupled with this as a `tmux-yank` option flag. In any case, on macOS this works.

**Comment by yevhen-m** [comment]
What's the status of this PR? I guess lots of `yank` users are waiting for it to be merged.

**Comment by yevhen-m** [comment]
I've tried to set 
```
# tmux-yank settings
set -g @yank_action 'copy-pipe'
```
But I still get kicked out from copy mode after I press `y` or release mouse selection. What am I doing wrong?

**Comment by maximbaz** [comment]
Have you restarted tmux? It worked for me.

**Comment by yevhen-m** [comment]
@maximbaz what os/terminal/tmux do you use?
Mine:
```
macos 10.13.3 
Build 3.1.6beta4
tmux/HEAD-06684c9
```

**Comment by maximbaz** [comment]
Try to reproduce also without using a mouse, enter copy mode, scroll up, select something and press `y`.

As for preserving the scroll after mouse selection, I have this in my `.tmux.conf`:

```
# Preserve mouse selection and scroll position after mouse drag
unbind -T copy-mode-vi MouseDragEnd1Pane
```

Full config for reference: https://github.com/maximbaz/dotfiles/blob/master/.tmux.conf

Note, I'm not using `set -g @yank_action 'copy-pipe'`, but when I tested I placed it after line 118.

```
Arch Linux 4.15.10
tmux 2.6
```

**Comment by yevhen-m** [comment]
Well, it kind of works when I use keyboard only. 
When I select something and hit `y`, selection is still there, text gets copied and I stay in copy-mode. Do you have the same behavior?

Also, your `unbind` line helped, now I can select text with mouse as well.

**Comment by yevhen-m** [comment]
I hoped that `y` would clear my selection but still leave my in copy mode and cursor at the same place. Can this be achieved somehow?

**Comment by maximbaz** [comment]
Yes, that's exactly how it looks for me - selection stays and you are not scrolled back to the bottom.

I guess it has to be a combination of `copy-pipe` and `clear-selection`, but I'm not sure what's the proper syntax to combine these...

**Comment by yevhen-m** [comment]
@maximbaz thanks for help. 
@kaliberr44 thanks for your PR.

I consider clearing selection and staying in copy mode very cool, so if anyone knows how to achieve this, please let us know.

**Comment by yevhen-m** [comment]
@maximbaz I've managed to bind keys like this:
```
bind-key -T copy-mode y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy" \; send-keys -X clear-selection
bind-key -T copy-mode Y send-keys -X copy-pipe-and-cancel "tmux paste-buffer"
bind-key -T copy-mode-vi y send-keys -X copy-pipe "reattach-to-user-namespace pbcopy" \; send-keys -X clear-selection
bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "tmux paste-buffer"
unbind   -T copy-mode MouseDragEnd1Pane
unbind   -T copy-mode-vi MouseDragEnd1Pane
```
I guess `reattach-to-user-namespace pbcopy` should be changed for other systems. Frankly speaking I don't need `tmux-yank` anymore cause I can't see any reasons to keep it my my `tmux.conf` any longer.

**Pull request merged**
