### PR TITLE
Add support for WSL

### PR DESCRIPTION
**Pull request by mdentremont**

### CODE REVIEW

**Comment by mdentremont** [comment]
This allows tmux-yank to work out of the box with [BashOnWindows](https://github.com/Microsoft/BashOnWindows) (with the Creator's Update or an insider build)

**Comment by oblitum** [comment]
@mdentremont that's interesting. OFF-TOPIC: out of curiosity, have you managed to make clip.exe work with vim or neovim clipboard?

**Comment by mdentremont** [comment]
@oblitum for neovim I just downloaded "win32yank.exe" from https://github.com/equalsraf/win32yank, and added a `win32yank` script in my bash path with the following contents:

```
#!/bin/bash

/mnt/c/<path to win32yank folder>/win32yank.exe "$@" 2>/dev/null
```

Props to @rygwdn for this :+1:

**Comment by mdentremont** [comment]
Oops didn't notice this other PR which does the same thing: https://github.com/tmux-plugins/tmux-yank/pull/79

**Comment by oblitum** [comment]
@mdentremont many thanks for the tips.

**Comment by oblitum** [comment]
@mdentremont worked (requires NeoVim unstable).

**Pull request closed without merging**
