### PR TITLE
Use clip.exe if exists for copying to Windows clipboard in WSL.

### PR DESCRIPTION
**Pull request by lukewang1024**

### CODE REVIEW

**Comment by oblitum** [comment]
When I select and press y it doesn't leave the selection, is it working for you? [I'm using win32yank](https://github.com/tmux-plugins/tmux-yank/pull/81#issuecomment-297517979) on NeoVim and it's workinf fine for copy and paste.

**Comment by lukewang1024** [comment]
This works for me with tmux 2.3 used on [Arch Linux in WSL](https://github.com/alwsl/alwsl).

Could it be `<prefix>+y` overwritten by accident? I have the following from the output of my `<prefix>+?`:
```
bind-key    -T prefix     y                run-shell -b /home/lukew/.tmux/plugins/tmux-yank/scripts/copy_line.sh
```

**Comment by oblitum** [comment]
@lukewang1024 wow, just checking alwsl again and since last time I checked they managed to get a nice sponsorship. I plan to switch as soon as I feel it more stable, are you having any instability?

I'll check my command output as soon as I boot Windows again.

**Comment by oblitum** [comment]
@lukewang1024 it works! The issue was this recent merge https://github.com/tmux-plugins/tmux-yank/pull/82#issuecomment-298272754.

**Comment by lukewang1024** [comment]
@oblitum Basically I use WSL for tmux, zsh, tig & web npm toolchains and alwsl works pretty fine so far. Worth a shot I bet;)

**Comment by oblitum** [comment]
@lukewang1024 just out of curiosity, I've just give it a day to try. It's not for prime time, many issues, for example https://github.com/Microsoft/BashOnWindows/issues/1878 is annoying, I dunno which programs will fail on that, right now locale-gen failed but there was a way out, clang is unusable.

**Pull request merged**
